---
engine: knitr
---

# Introduction to Averaging and Parameter Estimation {#sec-chap-10}

In this chapter the author explains and demonstrates how averaging of data works. This is not new territory for me, therefore I will skip the whole section and concentrate only on the exercises

## Exercises

Try answering the following questions to see how well you understand averaging to estimate an unknown measurement. The solutions can be found at [https://nostarch.com/learnbayes/](https://nostarch.com/learnbayes/).


### Exercise 10-1

It’s possible to get errors that don’t quite cancel out the way we want. In the Fahrenheit temperature scale, 98.6 degrees is the normal body temperature and 100.4 degrees is the typical threshold for a fever. Say you are taking care of a child that feels warm and seems sick, but you take repeated readings from the thermometer and they all read between 99.5 and 100.0 degrees: warm, but not quite a fever. You try the thermometer yourself and get several readings between 97.5 and 98. What could be wrong with the thermometer?

To have a better intuitive understand I am going to convert the data to the Celsius temperature scale:

In the Celsius temperature scale, 37.0 degrees is the normal body temperature and 38.0 degrees is the typical threshold for a fever. Say you are taking care of a child that feels warm and seems sick, but you take repeated readings from the thermometer and they all read between 37.5 and 37,8 degrees: warm, but not quite a fever. You try the thermometer yourself and get several readings between 36.4 and 36.7. What could be wrong with the thermometer?

**Solution**:

The thermometer is biased by approximately of 0.55 Grad Celsius (about 1 Grad Fahrenheit)

### Exercise 10-2

Given that you feel healthy and have traditionally had a very consistently normal temperature, how could you alter the measurements 100, 99.5, 99.6, and 100.2 to estimate if the child has a fever?

**Solution**:

Adding 0.55 Grad Celsius or 1 Grad Fahrenheit to the measured values.


