project:
  type: book

book:
  title: "Bayesian Statistics the Fun Way"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon.ico"

  chapters:
    - index.qmd
    - 00-intro.qmd
    - 01-everyday-reasoning.qmd
    - 02-measuring-uncertainty.qmd
    - 95-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: "glossary.css"
    number-sections: true
    toc-depth: 5
    toc-expand: 2
    code-fold: false
    code-tools: true
    code-link: true
    code-overflow: scroll
    df-print: default

editor: visual

knitr:
  opts_chunk:
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

execute:
    freeze: auto

language:
   crossref-fig-title: "Picture"
   crossref-prp-title: "Callout"

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
   callout-tip-title: "Resource"         # green
   callout-note-title: "Note"            # blue
   callout-warning-title: "Wach out!"    # orange
   callout-important-title: "Important"  # red
   callout-caution-title: "TODO"         # yellow

engine: knitr
